[frontend]
172.31.45.161

[catalogue]

[user]

[cart]

[shipping]

[payment]

[mongodb]

[redis]

[mysql]

[rabbitmq]

[roboshop:children]
frontend
catalogue
user
cart
shipping
payment
mongodb
redis
mysql
rabbitmq
